---
services:
  valo-trayb-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    environment:
      - BRAND_NAME=${BRAND_NAME:-Trayb}
      - BRAND_LOGO_URL=${BRAND_LOGO_URL:-/assets/misc/icon.webp}
      - SERVER_ENDPOINT=${SERVER_ENDPOINT:-https://data.trayb.az}
      - OVERLAY_ACCESS_TOKEN=${OVERLAY_ACCESS_TOKEN}
      - REDIRECT_URL=${REDIRECT_URL:-https://trayb.az}
      - EXTRAS_ENDPOINT=${EXTRAS_ENDPOINT:-https://extras.trayb.az}
